name: CI
on:
  pull_request:
    branches: 
      - main

env:
  COVEO_PLATFORM_ENV: 'stg'
jobs:
  qa-preview:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Login
        uses: ./.github/actions/login
        with:
          environment: ${{ env.COVEO_PLATFORM_ENV }}
          api-key: ${{ secrets.COVEO_API_KEY }}
      - name: Preview Changes
        uses: ./.github/actions/deploy